apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation
  template:
    metadata:
      labels:
        app: automation
    spec:
      containers:
      - name: automation
        image: your-dockerhub-username/automation:latest
        env:
        - name: BACKEND_URL
          value: "http://backend:5000"
